$(document).ready(function(){
	$(".center").slick({
		dots:false,
		infinite:true,
		slidesToShow:5,
		slidesToScroll:3,
		responsive:[
		{
			breakpoint:768,
			settings:{
				dots:false,
				infinite:true,
				slidesToShow:3,
				slidesToScroll:3,
			}
		},
		{
			breakpoint:480,
			settings:{
				dots:false,
				infinite:true,
				slidesToShow:1,
				slidesToScroll:1,
			}
		},
		]
	});
});

